export const places = [
    { city: 'Amsterdam', timezone: 'Europe/Amsterdam' },
    { city: 'Honolulu', timezone: 'Pacific/Honolulu' },
    { city: 'Taipei', timezone: 'Asia/Taipei' },
    { city: 'Istanbul', timezone: 'Asia/Istanbul' },
    { city: 'Nairobi', timezone: 'Africa/Nairobi' },
    { city: 'Auckland', timezone: 'Pacific/Auckland' },
    { city: "Kyiv", timezone: 'Europe/Kyiv' },
    { city: 'Rio de Janeiro', timezone: 'Brazil/East' },
    { city: 'Johannesburg', timezone: 'Africa/Johannesburg' },
    { city: 'Addis Ababa', timezone: 'Africa/Addis_Ababa' },
    { city: 'Singapore', timezone: 'Asia/Singapore' },
    { city: 'London/GMT', timezone: 'Europe/London' },
    { city: 'Jakarta', timezone: 'Asia/Jakarta' },
    { city: 'Moscow', timezone: 'Europe/Moscow' },
    { city: 'Los Angeles', timezone: 'America/Los_Angeles' },
    { city: 'Washington', timezone: 'America/Eastern' },
    { city: 'Bangkok', timezone: 'Asia/Bangkok' },
    { city: 'Jerusalem', timezone: 'Asia/Jerusalem' },
    { city: 'Dubai', timezone: 'Asia/Dubai'},
    { city: 'Lisbon', timezone: 'Europe/Lisbon' },
    { city: 'Rome', timezone: 'Europe/Rome' },
    { city: 'Edmonton', timezone: 'America/Edmonton' },
    { city: 'Mexico City', timezone: 'America/Mexico_City' },
    { city: 'Beijing', timezone: 'Asia/Shanghai' },
    { city: 'Pago Pago', timezone: 'Pacific/Pago_Pago' },
    { city: 'Melbourne', timezone: 'Australia/Melbourne' },
    { city: 'Helsinki', timezone: 'Europe/Helsinki'},
    { city: 'New Delhi', timezone: 'Asia/Kolkata' },
    { city: 'Reykjavik', timezone: 'Atlantic/Reykjavik' },
    { city: 'New York', timezone: 'America/New_York'},
    { city: 'Baghdad', timezone: 'Asia/Baghdad' },
    { city: 'Buenos Aires', timezone: 'America/Buenos_Aires' },
    { city: 'Hong Kong', timezone: 'Asia/Hong_Kong' },
    { city: 'Shanghai', timezone: 'Asia/Shanghai' },
    { city: 'Tokyo', timezone: 'Asia/Tokyo' },
    { city: 'Adelaide', timezone: 'Australia/Adelaide' },
    { city: 'Kuala Lumpur', timezone: 'Asia/Kuala_Lumpur' },
    { city: 'South Pole', timezone: 'Antarctica/South_Pole' },
    { city: 'Seoul', timezone: 'Asia/Seoul' },
    { city: 'Sydney', timezone: 'Australia/Sydney'}
];